New datasets
ProjetaAi/kedro-projetaai pull request #6
Opened 2023-09-05 16:11 UTC by ms-cmy

todas features testadas
lembrando que o código da feature é o readers.py, o extras.py está em alguns projetos e vai continuar por algumas semanas, depois que todos os projetos passarem a usar o readers.py (que está testado e com mais métodos) o extras.py será removido!!
features: ReadFile -> leitura com dtypes 
VersionedDataset -> path mais personalizado
PathReader -> retorna dataset dado uma janela histórica
LoadLast -> carrega o último arquivo

2023-09-05 18:23 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +# TODO: default load_config and save_config.
remover ou resolver

2023-09-05 18:36 UTC, gustavo-advisia requested changes

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        função do filesystem para ser usada na leitura
traduzir para inglês pra manter o padrão

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        Inicialização da classe
inglês

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        verifica se o dataset é versionado e pega a versão
ING

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +class ReadParquet(ParquetDataSet, BaseDataset):  # VendasDataSet
pode remover?

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +    # def _format_filepath_version(self) -> str:
remover se n precisa +

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        # Save the data to the formatted_filepath
pode remover tbm?

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        # arrumar p deixar mais organizado
já foi feito?

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        # essa função está rodando paralelizada
remover comment

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/datasets/extras.py
> +        # dfs = pd.concat(map(self._to_pandas_dataframe, path_list))
remover teste

2023-09-05 18:36 UTC, gustavo-advisia commented on tests/test_readers.py
> +# df = generate_dataframe(10, 2)
remover teste

2023-09-05 18:36 UTC, gustavo-advisia commented on kedro_projetaai/utils/readers.py
> +# TODO: default load_config and save_config.
já foram resolvidos?

2023-09-05 18:39 UTC, ms-cmy commented on kedro_projetaai/utils/datasets/extras.py
> +# TODO: default load_config and save_config.
já foi resolvido, esqueci de resolver

2023-09-06 16:48 UTC, juanengml approved these changes
Achei os tests ok, acredito que podemos liberar para release, ps quando essa release sair monta um doc sobre como isso impacta e o que ela resolve. Vamos mandar um email para os time de pricing e Site Location para serem os betas

2023-09-06 16:48 UTC, juanengml commented on tests/test_readers.py
> +        return
Não precisa desse return, retorna algo se tiver

2023-09-06 16:48 UTC, juanengml commented on tests/test_readers.py
> +        return
poderia remover aqui tambem o return

2023-09-06 16:48 UTC, juanengml commented on tests/test_readers.py
> +        return
Outro return perdido ! remover pls

2023-09-06 16:48 UTC, juanengml commented on tests/test_readers.py
> +        return
Outro return perdido ! remover pls

2023-09-06 16:48 UTC, juanengml commented on tests/test_readers.py
> +        return
Outro return perdido ! remover pls

2023-09-06 16:48 UTC, juanengml commented on tests/test_readers.py
> +        return
Outro return perdido ! remover pls

2023-09-06 17:24 UTC, ms-cmy commented on tests/test_readers.py
> +        return
é mais questão de code style, eu sempre gosto de colocar return em todas as minhas funções quando eu termino elas independente do return; pep8 por exemplo não veria problema. qualquer coisa podemos pensar em um code style para isso

2023-09-06 17:35 UTC, gustavo-advisia approved these changes

2023-09-06 18:56 UTC, merged